const list = [
    //get
    //题库
    { id: 331, url: '/api/class-question/used-courseware' },
    { id: 340, url: '/api/class-question/question-list' },
    { id: 393, url: '/api/product-log/comment-list' },
    { id: 332, url: '/api/class-question/used-online-courseware' },
    { id: 342, url: '/api/class-question/point-examine-result' },
    { id: 341, url: '/api/class-question/question-examine-result' },
    { id: 335, url: '/api/class-question/report' },
    { id: 336, url: '/api/class-question/recommend-list' },
    // 课件转换
    { id: 346, url: '/api/convert-courseware/update-status' },
    { id: 345, url: '/api/convert-courseware/detail' },
    { id: 386, url: '/api/courseware-favorite/list' },
    { id: 387, url: '/api/courseware-sharing/bought-subject' },
    { id: 388, url: '/api/courseware-online/subjects' },
    //老师端遗漏接口
    { id: 456, url: '/api/course-table/calendar-subjects' },
    { id: 457, url: '/api/course-table/teacher-plan-list' },
    { id: 503, url: '/api/course-table/dispose-list' },
    { id: 452, url: '/api/credit/index' },
    { id: 453, url: '/api/credit/salary-log' },
    { id: 455, url: '/api/credit/credit-log' },
    { id: 454, url: '/api/credit/task-list' },
    { id: 506, url: '/api/courseware-sharing/select-list' },
    { id: 469, url: '/api/feed-back/index' },
    { id: 468, url: '/api/faq/get-list' },
    { id: 532, url: '/api/teacher/class-log' },
    { id: 544, url: '/api/teacher/get-business-training-time' },
    { id: 540, url: '/api/teacher/get-teacher-level-log' },
    { id: 542, url: '/api/teacher/get-student-exam-type' },
    { id: 541, url: '/api/teacher/get-student-score-list' },
    { id: 531, url: '/api/teacher/student-data' },
    { id: 539, url: '/api/teacher/student-free-time' },
    { id: 535, url: '/api/teacher/get-teacher-experience-log' },
    { id: 536, url: '/api/teacher/get-teacher-experience-ranking' },
    { id: 538, url: '/api/teacher/get-class-and-product' },
    { id: 537, url: '/api/teacher/update-class-train-time' },
    { id: 430, url: '/api/teacher/teacher-data' },
    { id: 530, url: '/api/teacher/train-question' },
    { id: 533, url: '/api/teaching-class/class-detail' },
    { id: 521, url: '/api/user/courseware' },
    { id: 519, url: '/api/user' },
    { id: 512, url: '/api/courseware/report?id=' },
    { id: 492, url: '/api/courseware/detail' },
    { id: 490, url: '/api/rob-class/class-count' }, //抢课
    { id: 491, url: '/api/rob-class/index' },
    { id: 484, url: '/api/product-log/read' },
    { id: 487, url: '/api/message/notice' },
    { id: 488, url: '/api/message/list' },
    { id: 489, url: '/api/pre-sales/student-subject-detail' }, //没有返回
    { id: 527, url: '/api/user/convert-stat' },//没有返回
    { id: 474, url: '/api/salary/recommend' },
    { id: 475, url: '/api/salary/try' },
    { id: 477, url: '/api/salary/list' },
    { id: 479, url: '/api/salary/summary' },
    { id: 480, url: '/api/salary/apply-invite-teacher-list' },
    { id: 482, url: '/api/user-teaching-plan/detail' },
    // YiYou
    { id: 239, url: '/api/courseware-online/list' },
    { id: 234, url: '/api/courseware-online/del' },
    { id: 205, url: '/api/courseware-online/detail' },
    { id: 211, url: '/api/jing-you/region' },
    { id: 214, url: '/api/jing-you/subjects' },
    { id: 210, url: '/api/jing-you/books' },
    { id: 216, url: '/api/jing-you/subject-degree-list' },
    { id: 215, url: '/api/jing-you/subject-cate-list' },
    { id: 217, url: '/api/jing-you/subject-source' },
    { id: 208, url: '/api/jing-you/chapters' },
    { id: 209, url: '/api/jing-you/points' },
    { id: 212, url: '/api/jing-you/search-chapter' },
    { id: 213, url: '/api/jing-you/search-point' },
    { id: 218, url: '/api/jing-you/search-ques' },
    { id: 229, url: '/api/jing-you/point-card' },
    { id: 232, url: '/api/jing-you/detail' },
    { id: 271, url: '/api/jing-you/get-points' },
    { id: 224, url: '/api/teacher/get-sign-subject' },
    { id: 231, url: '/api/teacher/get-teacher-apply-medal' },
    { id: 228, url: '/api/teacher/get-self-medal-target-data' },
    { id: 267, url: '/api/jingyou-favorite/operate-favorite?action=list' },//收藏夹
    { id: 269, url: '/api/jingyou-favorite/operate-question?action=list' },//试题列表

    { id: 280, url: '/api/course-generate/class-notification-detail' },
    { id: 321, url: '/user/courseware/upload-auth' },
    { id: 323, url: '/user/courseware/check-exist' },


    //post
    //题库

    // 课件转换

    // 老师端遗漏接口
    { id: 433, url: '/api/teacher/tch-sign-contract' },
    { id: 434, url: '/api/course-table/add-dispose' },
    { id: 435, url: '/api/course-table/get-dispose-type' },
    { id: 436, url: '/api/course-table/teacher-add-class' },
    { id: 437, url: '/api/course-table/change-time' },
    { id: 438, url: '/api/courseware-sharing/buy' },
    { id: 439, url: '/api/courseware-sharing/comment' },
    { id: 440, url: '/api/courseware-sharing/comment-list' },
    { id: 441, url: '/api/courseware-sharing/like' },
    { id: 442, url: '/api/courseware-sharing/details' },
    { id: 443, url: '/api/courseware-sharing/share' },
    { id: 444, url: '/api/courseware-sharing/label' },
    { id: 334, url: '/api/class-question/point-examine' },
    { id: 333, url: '/api/class-question/question-examine' },
    { id: 448, url: '/api/feed-back/send' },
    { id: 230, url: '/api/teacher/teacher-apply-medal' },
    { id: 451, url: '/api/salary/apply-invite-teacher' },
    { id: 270, url: '/api/jingyou-favorite/operate-question?action=sort' },
    { id: 263, url: '/api/jingyou-favorite/operate-question?action=add' },
    { id: 266, url: '/api/jingyou-favorite/operate-favorite?action=update' },
    { id: 265, url: '/api/jingyou-favorite/operate-favorite?action=delete' },
    { id: 268, url: '/api/jingyou-favorite/operate-question?action=delete' },
    { id: 264, url: '/api/jingyou-favorite/operate-favorite?action=add' },
    { id: 382, url: '/api/courseware-favorite/update' },
    { id: 383, url: '/api/courseware-favorite/delete' },
    { id: 381, url: '/api/courseware-favorite/add' },
    { id: 384, url: '/api/courseware-favorite/move-courseware' },
    { id: 390, url: '/api/courseware-favorite/move-out-courseware' },
    { id: 385, url: '/api/courseware-favorite/delete-courseware' },
    { id: 322, url: '/user/courseware/fast-upload' },
    { id: 462, url: '/api/courseware-sharing/change-sale-type' },
    { id: 464, url: '/api/courseware/edit-name' },
    { id: 207, url: '/api/courseware-online/add' },
    { id: 467, url: '/api/jing-you/report' },
    { id: 339, url: '/api/class-question/complete' },
    { id: 470, url: '/api/teacher/student-all-subject-score' },
    { id: 471, url: '/api/teacher/update-target-score' },
    { id: 472, url: '/api/teacher/update-subject-exam-type' },
    { id: 476, url: '/api/teacher/teacher-update-student-data' },
    { id: 478, url: '/api/teacher/update-student-free-time' },
    { id: 481, url: '/api/credit/gift-list' },
    { id: 483, url: '/api/faq/feedback' },
    { id: 485, url: '/api/faq/faq-detail' },
    { id: 486, url: '/api/faq/reason-list' },
    { id: 396, url: '/api/class-question/comment' },
    { id: 395, url: '/api/class-question/score' },
    { id: 493, url: '/api/teacher/update-class-train-time' },
    { id: 494, url: '/api/teacher/train-answer' },
    { id: 495, url: '/api/message/read' },
    { id: 496, url: '/api/rob-class/rob-guide' },
    { id: 497, url: '/api/class/create' },
    { id: 498, url: '/api/credit/check-in' },
    { id: 500, url: '/api/teacher/receive-class' },
    { id: 501, url: '/api/teacher/remind' },
    { id: 502, url: '/api/product-log/comment' },
    { id: 504, url: '/api/message/read-all' },
    { id: 505, url: '/api/message/delete' },
    { id: 507, url: '/api/credit/get-reward' },
    { id: 508, url: '/api/teacher/update-mobile' },
    { id: 509, url: '/api/teacher/bind-mobile-captcha' },
    { id: 510, url: '/api/teacher/relieve-mobile-captcha' },
    { id: 511, url: '/api/teacher/audit-verification-code' },
    { id: 513, url: '/api/user/verification-nickname' },
    { id: 514, url: '/api/user/basic' },
    { id: 516, url: '/api/third-login/remove' },
    { id: 517, url: '/api/third-login/list' },
    { id: 518, url: '/api/user/card-photo' },
    { id: 520, url: '/api/user/life-photo' },
    { id: 522, url: '/api/user/tch-cert' },
    { id: 523, url: '/api/user/profile' },
    { id: 524, url: '/api/user/get-province' },
    { id: 525, url: '/api/user/password' },
    { id: 526, url: '/api/rob-class/robbery' },
];

const result = {};
list.forEach(item => {
    result[item.id] = item.url;
});

// export default result
export default list